"""voter referrals

Revision ID: 053a9fbcfdff
Revises: d3e7d3efd9d1
Create Date: 2026-09-25 10:50:27.128505
"""
from alembic import op
import sqlalchemy as sa


revision = '053a9fbcfdff'
down_revision = 'd3e7d3efd9d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voters', sa.Column('share_code', sa.String(length=12), nullable=True))
    op.add_column('voters', sa.Column('referred_by', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_voters_referred_by'), 'voters', ['referred_by'], unique=False)
    op.create_index(op.f('ix_voters_share_code'), 'voters', ['share_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voters_share_code'), table_name='voters')
    op.drop_index(op.f('ix_voters_referred_by'), table_name='voters')
    op.drop_column('voters', 'referred_by')
    op.drop_column('voters', 'share_code')
    # ### end Alembic commands ###
