"""public website content, volunteers, public events

Revision ID: 156084007b73
Revises: 297aab962030
Create Date: 2026-09-27 02:23:17.601232
"""
from alembic import op
import sqlalchemy as sa


revision = '156084007b73'
down_revision = '297aab962030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_posts',
    sa.Column('slug', sa.String(length=90), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_news_posts_created_at'), 'news_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_posts_published'), 'news_posts', ['published'], unique=False)
    op.create_index(op.f('ix_news_posts_published_at'), 'news_posts', ['published_at'], unique=False)
    op.create_table('site_pages',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_site_pages_created_at'), 'site_pages', ['created_at'], unique=False)
    op.create_table('volunteers',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('ward_id', sa.String(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('availability', sa.String(length=40), nullable=True),
    sa.Column('message', sa.String(length=600), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('handled_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteers_created_at'), 'volunteers', ['created_at'], unique=False)
    op.create_index(op.f('ix_volunteers_phone'), 'volunteers', ['phone'], unique=False)
    op.create_index(op.f('ix_volunteers_status'), 'volunteers', ['status'], unique=False)
    op.create_index(op.f('ix_volunteers_ward_id'), 'volunteers', ['ward_id'], unique=False)
    op.add_column('visits', sa.Column('public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'public')
    op.drop_index(op.f('ix_volunteers_ward_id'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_status'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_phone'), table_name='volunteers')
    op.drop_index(op.f('ix_volunteers_created_at'), table_name='volunteers')
    op.drop_table('volunteers')
    op.drop_index(op.f('ix_site_pages_created_at'), table_name='site_pages')
    op.drop_table('site_pages')
    op.drop_index(op.f('ix_news_posts_published_at'), table_name='news_posts')
    op.drop_index(op.f('ix_news_posts_published'), table_name='news_posts')
    op.drop_index(op.f('ix_news_posts_created_at'), table_name='news_posts')
    op.drop_table('news_posts')
    # ### end Alembic commands ###
