"""data subject requests

Revision ID: 297aab962030
Revises: 5998aabbf74c
Create Date: 2026-09-27 02:13:44.655710
"""
from alembic import op
import sqlalchemy as sa


revision = '297aab962030'
down_revision = '5998aabbf74c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_requests',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('handled_by_id', sa.String(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_requests_created_at'), 'data_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_requests_phone'), 'data_requests', ['phone'], unique=False)
    op.create_index(op.f('ix_data_requests_status'), 'data_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_requests_status'), table_name='data_requests')
    op.drop_index(op.f('ix_data_requests_phone'), table_name='data_requests')
    op.drop_index(op.f('ix_data_requests_created_at'), table_name='data_requests')
    op.drop_table('data_requests')
    # ### end Alembic commands ###
