"""mfa exemption

Revision ID: 2a80bd1793b2
Revises: c0b010cb0e3e
Create Date: 2026-09-25 21:23:49.612985
"""
from alembic import op
import sqlalchemy as sa


revision = '2a80bd1793b2'
down_revision = 'c0b010cb0e3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mfa_exempt_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_exempt_until')
    # ### end Alembic commands ###
