"""session activity

Revision ID: 2e50ceea03de
Revises: 053a9fbcfdff
Create Date: 2026-09-25 11:47:44.329206
"""
from alembic import op
import sqlalchemy as sa


revision = '2e50ceea03de'
down_revision = '053a9fbcfdff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('active_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'active_at')
    # ### end Alembic commands ###
