"""calendar events and field event kinds

Revision ID: 613249eea1da
Revises: 87d39622845b
Create Date: 2026-09-26 17:56:40.110791
"""
from alembic import op
import sqlalchemy as sa


revision = '613249eea1da'
down_revision = '87d39622845b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('constituency_id', sa.String(), nullable=True),
    sa.Column('ward_id', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hq_only', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('series_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_constituency_id'), 'calendar_events', ['constituency_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_created_at'), 'calendar_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_series_id'), 'calendar_events', ['series_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_starts_at'), 'calendar_events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_ward_id'), 'calendar_events', ['ward_id'], unique=False)
    op.add_column('visits', sa.Column('kind', sa.String(length=20), server_default='visit', nullable=False))
    op.add_column('visits', sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('visits', sa.Column('expected_attendance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'expected_attendance')
    op.drop_column('visits', 'ends_at')
    op.drop_column('visits', 'kind')
    op.drop_index(op.f('ix_calendar_events_ward_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_starts_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_series_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_created_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_constituency_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
