"""initial schema

Revision ID: 615232480eb0
Revises: 
Create Date: 2026-09-24 00:14:05.109390
"""
from alembic import op
import sqlalchemy as sa


revision = '615232480eb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE IF NOT EXISTS voter_ref_seq START 1")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constituencies',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('county', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_constituencies_created_at'), 'constituencies', ['created_at'], unique=False)
    op.create_table('wards',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('constituency_id', sa.String(), nullable=False),
    sa.Column('registered_voters', sa.Integer(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_wards_constituency_id'), 'wards', ['constituency_id'], unique=False)
    op.create_index(op.f('ix_wards_created_at'), 'wards', ['created_at'], unique=False)
    op.create_table('polling_stations',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('ward_id', sa.String(), nullable=False),
    sa.Column('streams', sa.Integer(), nullable=False),
    sa.Column('registered_voters', sa.Integer(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_polling_stations_created_at'), 'polling_stations', ['created_at'], unique=False)
    op.create_index(op.f('ix_polling_stations_ward_id'), 'polling_stations', ['ward_id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'coordinator', 'ward_coordinator', 'field_agent', 'call_agent', 'viewer', name='role'), nullable=False),
    sa.Column('constituency_id', sa.String(), nullable=True),
    sa.Column('ward_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('voters',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('national_id_enc', sa.Text(), nullable=False),
    sa.Column('national_id_hash', sa.String(length=64), nullable=False),
    sa.Column('national_id_last4', sa.String(length=4), nullable=False),
    sa.Column('voter_card_no', sa.String(length=40), nullable=True),
    sa.Column('gender', sa.Enum('female', 'male', 'other', name='gender'), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('support', sa.Enum('supporter', 'leaning', 'undecided', 'opposed', 'unknown', name='support'), nullable=False),
    sa.Column('source', sa.Enum('field', 'portal', 'call_centre', 'import', name='source'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected', name='status'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=240), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('capture_lat', sa.Float(), nullable=True),
    sa.Column('capture_lng', sa.Float(), nullable=True),
    sa.Column('captured_by_id', sa.String(), nullable=True),
    sa.Column('verified_by_id', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['captured_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['polling_stations.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id_hash'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_voters_captured_by_id'), 'voters', ['captured_by_id'], unique=False)
    op.create_index(op.f('ix_voters_created_at'), 'voters', ['created_at'], unique=False)
    op.create_index(op.f('ix_voters_full_name'), 'voters', ['full_name'], unique=False)
    op.create_index(op.f('ix_voters_opted_out'), 'voters', ['opted_out'], unique=False)
    op.create_index(op.f('ix_voters_phone'), 'voters', ['phone'], unique=False)
    op.create_index(op.f('ix_voters_source'), 'voters', ['source'], unique=False)
    op.create_index(op.f('ix_voters_station_id'), 'voters', ['station_id'], unique=False)
    op.create_index(op.f('ix_voters_status'), 'voters', ['status'], unique=False)
    op.create_index(op.f('ix_voters_support'), 'voters', ['support'], unique=False)
    op.create_index(op.f('ix_voters_ward_id'), 'voters', ['ward_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voters_ward_id'), table_name='voters')
    op.drop_index(op.f('ix_voters_support'), table_name='voters')
    op.drop_index(op.f('ix_voters_status'), table_name='voters')
    op.drop_index(op.f('ix_voters_station_id'), table_name='voters')
    op.drop_index(op.f('ix_voters_source'), table_name='voters')
    op.drop_index(op.f('ix_voters_phone'), table_name='voters')
    op.drop_index(op.f('ix_voters_opted_out'), table_name='voters')
    op.drop_index(op.f('ix_voters_full_name'), table_name='voters')
    op.drop_index(op.f('ix_voters_created_at'), table_name='voters')
    op.drop_index(op.f('ix_voters_captured_by_id'), table_name='voters')
    op.drop_table('voters')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_polling_stations_ward_id'), table_name='polling_stations')
    op.drop_index(op.f('ix_polling_stations_created_at'), table_name='polling_stations')
    op.drop_table('polling_stations')
    op.drop_index(op.f('ix_wards_created_at'), table_name='wards')
    op.drop_index(op.f('ix_wards_constituency_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_constituencies_created_at'), table_name='constituencies')
    op.drop_table('constituencies')
    # ### end Alembic commands ###
    for t in ("status", "source", "support", "gender", "role"):
        op.execute(f"DROP TYPE IF EXISTS {t}")
    op.execute("DROP SEQUENCE IF EXISTS voter_ref_seq")
