"""session portal

Revision ID: 6fb8133795e1
Revises: 9932d7d637cb
Create Date: 2026-09-24 11:38:34.965991
"""
from alembic import op
import sqlalchemy as sa


revision = '6fb8133795e1'
down_revision = '9932d7d637cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('portal', sa.String(length=10), server_default='command', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'portal')
    # ### end Alembic commands ###
