"""passkeys, step-up sessions, known devices

Revision ID: 9932d7d637cb
Revises: c63d7ea4943b
Create Date: 2026-09-24 10:16:55.511066
"""
from alembic import op
import sqlalchemy as sa


revision = '9932d7d637cb'
down_revision = 'c63d7ea4943b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_challenges',
    sa.Column('purpose', sa.Enum('register', 'login', 'second_factor', 'step_up', name='challenge_purpose'), nullable=False),
    sa.Column('challenge', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_challenges_created_at'), 'auth_challenges', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_challenges_user_id'), 'auth_challenges', ['user_id'], unique=False)
    op.create_table('known_devices',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('first_ip', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_known_devices_created_at'), 'known_devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_known_devices_device_hash'), 'known_devices', ['device_hash'], unique=False)
    op.create_index(op.f('ix_known_devices_user_id'), 'known_devices', ['user_id'], unique=False)
    op.create_table('passkeys',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.JSON(), nullable=True),
    sa.Column('aaguid', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('backed_up', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_index(op.f('ix_passkeys_created_at'), 'passkeys', ['created_at'], unique=False)
    op.create_index(op.f('ix_passkeys_user_id'), 'passkeys', ['user_id'], unique=False)
    op.add_column('user_sessions', sa.Column('auth_method', sa.String(length=20), server_default='password', nullable=False))
    op.add_column('user_sessions', sa.Column('elevated_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('passkey_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passkey_count')
    op.drop_column('user_sessions', 'elevated_until')
    op.drop_column('user_sessions', 'auth_method')
    op.drop_index(op.f('ix_passkeys_user_id'), table_name='passkeys')
    op.drop_index(op.f('ix_passkeys_created_at'), table_name='passkeys')
    op.drop_table('passkeys')
    op.drop_index(op.f('ix_known_devices_user_id'), table_name='known_devices')
    op.drop_index(op.f('ix_known_devices_device_hash'), table_name='known_devices')
    op.drop_index(op.f('ix_known_devices_created_at'), table_name='known_devices')
    op.drop_table('known_devices')
    op.drop_index(op.f('ix_auth_challenges_user_id'), table_name='auth_challenges')
    op.drop_index(op.f('ix_auth_challenges_created_at'), table_name='auth_challenges')
    op.drop_table('auth_challenges')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS challenge_purpose")
