"""invitations and staff photos

Revision ID: b4c445b1ef17
Revises: c06ac1e2d9ec
Create Date: 2026-09-24 16:21:35.217347
"""
from alembic import op
import sqlalchemy as sa


revision = 'b4c445b1ef17'
down_revision = 'c06ac1e2d9ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invites',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_invites_created_at'), 'user_invites', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_invites_user_id'), 'user_invites', ['user_id'], unique=False)
    op.add_column('users', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    # Everyone who exists before invitations were introduced is already active.
    op.execute("UPDATE users SET activated_at = created_at")
    op.add_column('users', sa.Column('photo_path', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('photo_sha256', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('photo_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_updated_at')
    op.drop_column('users', 'photo_sha256')
    op.drop_column('users', 'photo_path')
    op.drop_column('users', 'activated_at')
    op.drop_index(op.f('ix_user_invites_user_id'), table_name='user_invites')
    op.drop_index(op.f('ix_user_invites_created_at'), table_name='user_invites')
    op.drop_table('user_invites')
    # ### end Alembic commands ###
