"""sip accounts and call recordings

Revision ID: c06ac1e2d9ec
Revises: eb1c97c95887
Create Date: 2026-09-24 15:50:57.379458
"""
from alembic import op
import sqlalchemy as sa


revision = 'c06ac1e2d9ec'
down_revision = 'eb1c97c95887'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sip_accounts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('sip_user', sa.String(length=80), nullable=False),
    sa.Column('sip_password_enc', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_sip_accounts_created_at'), 'sip_accounts', ['created_at'], unique=False)
    op.create_table('call_recordings',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('voter_id', sa.String(), nullable=True),
    sa.Column('call_log_id', sa.String(), nullable=True),
    sa.Column('dialled_last4', sa.String(length=4), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('line', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_recordings_agent_id'), 'call_recordings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_call_recordings_call_log_id'), 'call_recordings', ['call_log_id'], unique=False)
    op.create_index(op.f('ix_call_recordings_created_at'), 'call_recordings', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_recordings_voter_id'), 'call_recordings', ['voter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_recordings_voter_id'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_created_at'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_call_log_id'), table_name='call_recordings')
    op.drop_index(op.f('ix_call_recordings_agent_id'), table_name='call_recordings')
    op.drop_table('call_recordings')
    op.drop_index(op.f('ix_sip_accounts_created_at'), table_name='sip_accounts')
    op.drop_table('sip_accounts')
    # ### end Alembic commands ###
