"""campaign plan

Revision ID: c0b010cb0e3e
Revises: 2e50ceea03de
Create Date: 2026-09-25 11:49:26.177030
"""
from alembic import op
import sqlalchemy as sa


revision = 'c0b010cb0e3e'
down_revision = '2e50ceea03de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_weeks',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_weeks_created_at'), 'plan_weeks', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_weeks_week_start'), 'plan_weeks', ['week_start'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_weeks_week_start'), table_name='plan_weeks')
    op.drop_index(op.f('ix_plan_weeks_created_at'), table_name='plan_weeks')
    op.drop_table('plan_weeks')
    # ### end Alembic commands ###
