"""phase 2: sessions, 2fa, messaging, visits, calls, election

Revision ID: c63d7ea4943b
Revises: 615232480eb0
Create Date: 2026-09-24 08:17:13.442226
"""
from alembic import op
import sqlalchemy as sa


revision = 'c63d7ea4943b'
down_revision = '615232480eb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_settings',
    sa.Column('election_date', sa.Date(), nullable=True),
    sa.Column('polls_open', sa.String(length=5), nullable=False),
    sa.Column('polls_close', sa.String(length=5), nullable=False),
    sa.Column('candidate_label', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_election_settings_created_at'), 'election_settings', ['created_at'], unique=False)
    op.create_table('message_campaigns',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'whatsapp', name='channel'), nullable=False),
    sa.Column('kind', sa.Enum('broadcast', 'visit', 'gotv', name='campaign_kind'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending_approval', 'scheduled', 'sending', 'sent', 'cancelled', 'rejected', name='campaign_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('reviewed_by_id', sa.String(), nullable=True),
    sa.Column('review_note', sa.String(length=240), nullable=True),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('recipients', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_campaigns_created_at'), 'message_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_campaigns_scheduled_at'), 'message_campaigns', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_message_campaigns_status'), 'message_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_message_campaigns_visit_id'), 'message_campaigns', ['visit_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('call_logs',
    sa.Column('voter_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('queue', sa.Enum('verify', 'persuade', 'gotv', 'follow_up', name='call_queue'), nullable=False),
    sa.Column('outcome', sa.Enum('answered', 'no_answer', 'busy', 'call_back', 'wrong_number', 'do_not_call', name='call_outcome'), nullable=False),
    sa.Column('support_after', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_done', sa.Boolean(), nullable=False),
    sa.Column('issue', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_agent_id'), 'call_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_call_logs_created_at'), 'call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_logs_follow_up_at'), 'call_logs', ['follow_up_at'], unique=False)
    op.create_index(op.f('ix_call_logs_outcome'), 'call_logs', ['outcome'], unique=False)
    op.create_index(op.f('ix_call_logs_voter_id'), 'call_logs', ['voter_id'], unique=False)
    op.create_table('messages',
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('voter_id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'failed', name='message_status'), nullable=False),
    sa.Column('provider_id', sa.String(length=120), nullable=True),
    sa.Column('error', sa.String(length=240), nullable=True),
    sa.Column('cost', sa.String(length=40), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['message_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'voter_id', name='uq_message_campaign_voter')
    )
    op.create_index(op.f('ix_messages_campaign_id'), 'messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_phone'), 'messages', ['phone'], unique=False)
    op.create_index(op.f('ix_messages_provider_id'), 'messages', ['provider_id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_voter_id'), 'messages', ['voter_id'], unique=False)
    op.create_table('visits',
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('ward_id', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('venue', sa.String(length=160), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='visit_status'), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('announce', sa.Boolean(), nullable=False),
    sa.Column('announce_hours_before', sa.Integer(), nullable=False),
    sa.Column('announcement_campaign_id', sa.String(), nullable=True),
    sa.Column('checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkin_by_id', sa.String(), nullable=True),
    sa.Column('checkin_lat', sa.Float(), nullable=True),
    sa.Column('checkin_lng', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_campaign_id'], ['message_campaigns.id'], ),
    sa.ForeignKeyConstraint(['checkin_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['polling_stations.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_created_at'), 'visits', ['created_at'], unique=False)
    op.create_index(op.f('ix_visits_scheduled_at'), 'visits', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_visits_status'), 'visits', ['status'], unique=False)
    op.create_index(op.f('ix_visits_ward_id'), 'visits', ['ward_id'], unique=False)
    op.add_column('users', sa.Column('failed_logins', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('totp_secret_enc', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('voters', sa.Column('client_ref', sa.String(length=64), nullable=True))
    op.add_column('voters', sa.Column('do_not_call', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('voters', sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('voters', sa.Column('call_locked_by_id', sa.String(), nullable=True))
    op.add_column('voters', sa.Column('call_locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('voters', sa.Column('voted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('voters', sa.Column('voted_marked_by_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_voters_voted_at'), 'voters', ['voted_at'], unique=False)
    op.create_unique_constraint('uq_voters_client_ref', 'voters', ['client_ref'])
    op.create_foreign_key('fk_voters_call_locked_by', 'voters', 'users', ['call_locked_by_id'], ['id'])
    op.create_foreign_key('fk_voters_voted_marked_by', 'voters', 'users', ['voted_marked_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_voters_voted_marked_by', 'voters', type_='foreignkey')
    op.drop_constraint('fk_voters_call_locked_by', 'voters', type_='foreignkey')
    op.drop_constraint('uq_voters_client_ref', 'voters', type_='unique')
    op.drop_index(op.f('ix_voters_voted_at'), table_name='voters')
    op.drop_column('voters', 'voted_marked_by_id')
    op.drop_column('voters', 'voted_at')
    op.drop_column('voters', 'call_locked_until')
    op.drop_column('voters', 'call_locked_by_id')
    op.drop_column('voters', 'last_contacted_at')
    op.drop_column('voters', 'do_not_call')
    op.drop_column('voters', 'client_ref')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret_enc')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_logins')
    op.drop_index(op.f('ix_visits_ward_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_status'), table_name='visits')
    op.drop_index(op.f('ix_visits_scheduled_at'), table_name='visits')
    op.drop_index(op.f('ix_visits_created_at'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_messages_voter_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_provider_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_phone'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_campaign_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_call_logs_voter_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_outcome'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_follow_up_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_created_at'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_agent_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_message_campaigns_visit_id'), table_name='message_campaigns')
    op.drop_index(op.f('ix_message_campaigns_status'), table_name='message_campaigns')
    op.drop_index(op.f('ix_message_campaigns_scheduled_at'), table_name='message_campaigns')
    op.drop_index(op.f('ix_message_campaigns_created_at'), table_name='message_campaigns')
    op.drop_table('message_campaigns')
    op.drop_index(op.f('ix_election_settings_created_at'), table_name='election_settings')
    op.drop_table('election_settings')
    # ### end Alembic commands ###
    for t in ("channel", "campaign_kind", "campaign_status", "message_status", "visit_status", "call_queue", "call_outcome"):
        op.execute(f"DROP TYPE IF EXISTS {t}")
