"""visit photos

Revision ID: d3e7d3efd9d1
Revises: f9b3b61f846b
Create Date: 2026-09-25 00:02:56.104156
"""
from alembic import op
import sqlalchemy as sa


revision = 'd3e7d3efd9d1'
down_revision = 'f9b3b61f846b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_photos',
    sa.Column('visit_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(length=80), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('taken_by_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taken_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_photos_created_at'), 'visit_photos', ['created_at'], unique=False)
    op.create_index(op.f('ix_visit_photos_visit_id'), 'visit_photos', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_photos_visit_id'), table_name='visit_photos')
    op.drop_index(op.f('ix_visit_photos_created_at'), table_name='visit_photos')
    op.drop_table('visit_photos')
    # ### end Alembic commands ###
