"""media labels and agenda items

Revision ID: de6a9d027464
Revises: 3c3b06a91c0f
Create Date: 2026-09-27 15:34:47.942120
"""
from alembic import op
import sqlalchemy as sa


revision = 'de6a9d027464'
down_revision = '3c3b06a91c0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_items',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cover_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_id'], ['site_media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_items_created_at'), 'agenda_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_agenda_items_position'), 'agenda_items', ['position'], unique=False)
    op.add_column('site_media', sa.Column('label', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_media', 'label')
    op.drop_index(op.f('ix_agenda_items_position'), table_name='agenda_items')
    op.drop_index(op.f('ix_agenda_items_created_at'), table_name='agenda_items')
    op.drop_table('agenda_items')
    # ### end Alembic commands ###
