"""agent presence

Revision ID: eb1c97c95887
Revises: 6fb8133795e1
Create Date: 2026-09-24 11:48:25.745586
"""
from alembic import op
import sqlalchemy as sa


revision = 'eb1c97c95887'
down_revision = '6fb8133795e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_presence',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('available', 'ringing', 'on_call', 'wrap_up', 'away', name='agent_status'), nullable=False),
    sa.Column('voter_id', sa.String(), nullable=True),
    sa.Column('status_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('line', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_agent_presence_created_at'), 'agent_presence', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_presence_heartbeat_at'), 'agent_presence', ['heartbeat_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_presence_heartbeat_at'), table_name='agent_presence')
    op.drop_index(op.f('ix_agent_presence_created_at'), table_name='agent_presence')
    op.drop_table('agent_presence')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS agent_status")
