"""Keep the PBX's agent lines in step with the platform (runs every 30 s in the container).

Pulls GET <backend>/calls/pbx/lines (X-PBX-Secret), writes pjsip_agents.conf with one
WebRTC endpoint per active line, and the ring-all group for inbound calls into AstDB.
Reloads Asterisk only when something changed. A line HQ removes, or a person who is
deactivated, stops working within a minute."""
import json
import os
import re
import subprocess
import sys
import time
import urllib.request

CONF = "/etc/asterisk/pjsip_agents.conf"
URL = os.environ.get("PBX_BACKEND_URL", "http://127.0.0.1:8090/api/v1").rstrip("/") + "/calls/pbx/lines"
SECRET = os.environ.get("PBX_SYNC_SECRET", "")
SAFE = re.compile(r"^[A-Za-z0-9_.+-]{2,80}$")

BLOCK = """
[{ext}]
type = endpoint
transport = transport-ws
context = from-agents
disallow = all
allow = ulaw
allow = alaw
webrtc = yes
auth = {ext}
aors = {ext}
direct_media = no
dtmf_mode = rfc4733
; {name}

[{ext}]
type = auth
auth_type = userpass
username = {ext}
password = {password}

[{ext}]
type = aor
max_contacts = 1
remove_existing = yes
"""


def ast(cmd: str) -> None:
    subprocess.run(["asterisk", "-rx", cmd], check=False, capture_output=True)


def fetch() -> list[dict] | None:
    req = urllib.request.Request(URL, headers={"X-PBX-Secret": SECRET})
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            return json.loads(r.read())
    except Exception as exc:
        print(f"sync: backend unreachable ({exc}); keeping current lines", flush=True)
        return None


def render(lines: list[dict]) -> str:
    out = ["; generated by sync_agents.py; do not edit"]
    for ln in lines:
        ext, pw = str(ln.get("ext", "")), str(ln.get("password", ""))
        if not SAFE.match(ext) or not pw or "\n" in pw:
            print(f"sync: skipping unusable line {ext!r}", flush=True)
            continue
        out.append(BLOCK.format(ext=ext, password=pw, name=re.sub(r"[^\w .'-]", "", str(ln.get("name", "")))[:60]))
    return "\n".join(out) + "\n"


def once() -> None:
    lines = fetch()
    if lines is None:
        return
    text = render(lines)
    old = open(CONF).read() if os.path.exists(CONF) else ""
    if text != old:
        with open(CONF, "w") as f:
            f.write(text)
        ast("pjsip reload")
        print(f"sync: {len(lines)} line(s) provisioned", flush=True)
    ring = "&".join(f"PJSIP/{ln['ext']}" for ln in lines if SAFE.match(str(ln.get("ext", ""))))
    if ring:
        ast(f"database put shahbal ringall {ring}")
    else:
        ast("database del shahbal ringall")


if __name__ == "__main__":
    if not SECRET:
        sys.exit("PBX_SYNC_SECRET is not set")
    while True:
        once()
        if "--once" in sys.argv:
            break
        time.sleep(30)
